### ISSUE TITLE
Update post 6

### ISSUE THREAD

**Issue by sngo25** [linagora/openpaas-tip-of-the-day#21]
esn-config API now supports promise, getting configuration by domain and module

**Comment by chamerling** [comment]
I think that we should use medium for these tips, there is no added value of setting things here

**Comment by chamerling** [comment]
ie medium/openpaas-tips or medium/openpaas-hacks

**Comment by sngo25** [comment]
I didn't know that. But does medium support collaboration? I prefer Jekyll, it's more programming way and the post is trackable (commit history)
